# Generated by Django 4.1 on 2024-04-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2023-11-12 11:15:35"
            ),
            preserve_default=False,
        ),
    ]
