# Generated by Django 5.0.3 on 2024-03-26 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_remove_comment_website_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="recipe",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.recipe",
            ),
        ),
    ]
